import { Global, ThemeProvider, css, Theme } from '@emotion/react'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { elekibear } from '@/theme/theme'

// グローバルのスタイル
const styleGlobal = (theme: Theme) => css`
  html,
  body,
  textarea {
    margin: 0;
    padding: 0;
    font-family: 'Helvetica Neue', Arial, 'Hiragino Kaku Gothic ProN',
      'Hiragino Sans', 'BIZ UDPGothic', Meiryo, sans-serif;
  }
  body {
    /** チェック柄 */
    background: linear-gradient(
        45deg,
        #2a2a2a 25%,
        transparent 25%,
        transparent 75%,
        #2a2a2a 75%
      ),
      linear-gradient(
        45deg,
        #2a2a2a 25%,
        transparent 25%,
        transparent 75%,
        #2a2a2a 75%
      );
    background-color: ${theme.colors.primaryDarkGray};
    background-size: 60px 60px;
    background-position:
      0 0,
      30px 30px;
  }
`

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Next.js × Emotion サンプル</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={elekibear}>
        <Global styles={styleGlobal} />
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  )
}
